# Generated by Django 6.0.7 on 2026-07-14 20:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('named_invite_mode', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrototypeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('html_content', models.TextField()),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('size', models.PositiveIntegerField(editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prototypes.prototype')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='prototype',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='prototypes.prototypeversion'),
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('domain', 'Domain'), ('email', 'Email')], max_length=10)),
                ('value', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='prototypes.prototype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prototype', 'kind', 'value'), name='unique_rule_per_prototype')],
            },
        ),
        migrations.AddConstraint(
            model_name='prototypeversion',
            constraint=models.UniqueConstraint(fields=('prototype', 'version_number'), name='unique_version_per_prototype'),
        ),
    ]
