# Generated by Django 6.0.7 on 2026-07-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='access_mode',
            field=models.CharField(choices=[('restricted', 'Restricted'), ('public', 'Anyone with the link')], default='restricted', max_length=12),
        ),
    ]
