# Generated by Django 6.0.7 on 2026-07-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prototypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('feedback_type', models.CharField(choices=[('question', 'Question'), ('change', 'Change'), ('bug', 'Bug'), ('other', 'Other')], default='other', max_length=10)),
                ('note', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('anchors', models.JSONField(blank=True, default=list)),
                ('css_selector', models.CharField(blank=True, max_length=1000)),
                ('element_snapshot', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=2000)),
                ('viewport', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='prototypes.prototypeversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.annotation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
