# Generated by Django 6.0.7 on 2026-07-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(default='image/webp', max_length=40)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shot', to='feedback.annotation')),
            ],
        ),
    ]
