# Generated by Django 6.0.7 on 2026-07-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_allow_domain',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='is_provisional',
            field=models.BooleanField(default=False),
        ),
    ]
